---
- name: create local dir for nifi key
  local_action: file path="keys/" state=directory mode=0755

- name: create nifi key pair
  ec2_key:
    region: "{{ region }}"
    name: "{{ nifi_key_name }}"
    state: present
  register: nifi_key_pair

### create iam roles
- name: copy redshift policy
  copy: src=../files/redshift_policy.json dest=/tmp/redshift_policy.json

- name: copy firehose delivery policy
  copy: src=../files/firehose_delivery_policy.json dest=/tmp/firehose_delivery_policy.json

- name: create redshift role
  shell: aws iam create-role --role-name {{redshift_role_name}} --assume-role-policy-document file:///tmp/redshift_policy.json
  ignore_errors: true

- name: create firehose role
  shell: aws iam create-role --role-name {{firehose_delivery_role_name}} --assume-role-policy-document file:///tmp/firehose_delivery_policy.json
  ignore_errors: true
###################################
### add policies to firehose role
- name: add s3 full access for firehose role
  shell: aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess --role-name {{firehose_delivery_role_name}}

- name: add full access to redshift for firehose role
  shell: aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonRedshiftFullAccess --role-name {{firehose_delivery_role_name}}

- name: add full access to kinesis for firehose role
  shell: aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonKinesisFullAccess --role-name {{firehose_delivery_role_name}}

- name: add full access to firehose delivery streams for firehose role
  shell: aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess --role-name {{firehose_delivery_role_name}}
###################################

##### add policies to redshift role
- name: add s3 full access policy for redshift role
  shell: aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess --role-name {{redshift_role_name}}

- name: allow access to manage S3 settings for Redshift endpoints for DMS.
  shell: aws iam attach-role-policy --policy-arn arn:aws:iam::aws:policy/service-role/AmazonDMSRedshiftS3Role --role-name {{redshift_role_name}}
###################################
- name: get firehose role
  shell: aws iam get-role --role-name {{firehose_delivery_role_name}}
  register: raw_firehose_role_info

- name: get redshift role
  shell: aws iam get-role --role-name {{redshift_role_name}}
  register: raw_redshift_role_info

- set_fact: firehose_role_info="{{ raw_firehose_role_info.stdout | from_json }}"

- set_fact: redshift_role_info="{{ raw_redshift_role_info.stdout | from_json }}"

- set_fact: firehose_role_arn="{{firehose_role_info.Role.Arn}}"
- set_fact: redshift_role_arn="{{redshift_role_info.Role.Arn}}"

# - debug: var=firehose_role_arn
# - debug: var=redshift_role_arn

- name: create key dir
  local_action: file path="keys/" state=directory mode=0755

- name: save nifi key pair
  local_action: copy content="{{ item.value.private_key }}" dest="{{ nifi_key_pair_file_name}}" mode=600
  with_dict: nifi_key_pair
  when: item.value.private_key is defined

- name: template redshift cluster script
  template: src=../templates/redshift_cluster.py.j2 dest=/tmp/redshift_cluster.py

- name: create redshift cluster. This can take some time.
  shell: python /tmp/redshift_cluster.py

- name: template delivery_stream script
  template: src=../templates/delivery_stream.py.j2 dest=/tmp/delivery_stream.py

- name: create delivery stream
  shell: python /tmp/delivery_stream.py

- get_jdbc:
    cluster_id: "{{ cluster_id }}"
    vpc_id: "{{ vpc_id }}"
    db_name: "{{ db_name }}"
    region: "{{ region }}"
  register: jdbc_results

- name: create nifi instance
  ec2:
    region: "{{ region }}"
    key_name: "{{ nifi_key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    group_id: "{{ sg_ids[0] }}"
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ vpc_subnet_ids[0] }}"
    assign_public_ip: yes
    instance_tags:
      Name: "nifi"
    count_tag:
      Name: "nifi"
    exact_count: 1
  register: ec2_result

- name: Wait for SSH ports
  wait_for: host={{ ec2_result.tagged_instances[0].public_ip }} port=22 delay=20 timeout=500 state=started

- name: Add instance to nifi group
  add_host:
    name: "{{ ec2_result.tagged_instances[0].public_ip }}"
    ansible_ssh_private_key_file: "{{ nifi_key_pair_file_name }}"
    ansible_host_key_checking: False
    groups: "nifi"
